/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/Archive.vue')['default']
    Aside: typeof import('./src/components/Aside/index.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeText: typeof import('./src/components/HomeText.vue')['default']
    Info: typeof import('./src/components/Aside/Info.vue')['default']
    LinkList: typeof import('./src/components/LinkList.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    RecentArticles: typeof import('./src/components/Aside/RecentArticles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortList: typeof import('./src/components/ShortList.vue')['default']
    ShortsList: typeof import('./src/components/ShortList.vue')['default']
    SvgIcon: typeof import('./src/components/Aside/SvgIcon.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TagCategoryList: typeof import('./src/components/TagCategoryList.vue')['default']
    Tags: typeof import('./src/components/Aside/Tags.vue')['default']
    Toc: typeof import('./src/components/Aside/Toc.vue')['default']
    Twikoo: typeof import('./src/components/Twikoo.vue')['default']
    UseTheme: typeof import('./src/components/useTheme.vue')['default']
    WebInfo: typeof import('./src/components/Aside/WebInfo.vue')['default']
  }
}
