/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/Archive.vue')['default']
    Aside: typeof import('./src/components/Aside/index.vue')['default']
    Cark: typeof import('./src/components/Cark.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Categorys: typeof import('./src/components/Categorys.vue')['default']
    Content: typeof import('./src/components/Contents.vue')['default']
    Contents: typeof import('./src/components/Contents.vue')['default']
    copy: typeof import('./src/components/Tag copy.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeText: typeof import('./src/components/HomeText.vue')['default']
    Info: typeof import('./src/components/Aside/Info.vue')['default']
    ListPost: typeof import('./src/components/PostsList.vue')['default']
    ListPosts: typeof import('./src/components/PostsList.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    PostsTitle: typeof import('./src/components/PostsTitle.vue')['default']
    RecentArticles: typeof import('./src/components/Aside/RecentArticles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgBG: typeof import('./src/components/SvgBG.vue')['default']
    SvgIcon: typeof import('./src/components/Aside/SvgIcon.vue')['default']
    SvgIconok: typeof import('./src/components/SvgIconok.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TagCategory: typeof import('./src/components/TagCategory.vue')['default']
    TagCategoryList: typeof import('./src/components/TagCategoryList.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    Tags: typeof import('./src/components/Aside/Tags.vue')['default']
    Text5: typeof import('./src/components/HomeText.vue')['default']
    Toc: typeof import('./src/components/Aside/Toc.vue')['default']
    Tw: typeof import('./src/components/Twikoo.vue')['default']
    Twikoo: typeof import('./src/components/Twikoo.vue')['default']
    UseTheme: typeof import('./src/components/useTheme.vue')['default']
    WebInfo: typeof import('./src/components/Aside/WebInfo.vue')['default']
  }
}
