/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/category/': RouteRecordInfo<'/category/', '/category', Record<never, never>, Record<never, never>>,
    '/category/[category]': RouteRecordInfo<'/category/[category]', '/category/:category', { category: ParamValue<true> }, { category: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/api-examples': RouteRecordInfo<'/posts/api-examples', '/posts/api-examples', Record<never, never>, Record<never, never>>,
    '/posts/api-examples copy': RouteRecordInfo<'/posts/api-examples copy', '/posts/api-examples copy', Record<never, never>, Record<never, never>>,
    '/posts/api-examples copy 2': RouteRecordInfo<'/posts/api-examples copy 2', '/posts/api-examples copy 2', Record<never, never>, Record<never, never>>,
    '/posts/api-examples copy 3': RouteRecordInfo<'/posts/api-examples copy 3', '/posts/api-examples copy 3', Record<never, never>, Record<never, never>>,
    '/posts/api-examples copy 4': RouteRecordInfo<'/posts/api-examples copy 4', '/posts/api-examples copy 4', Record<never, never>, Record<never, never>>,
    '/posts/api-examples copy 5': RouteRecordInfo<'/posts/api-examples copy 5', '/posts/api-examples copy 5', Record<never, never>, Record<never, never>>,
    '/posts/mk': RouteRecordInfo<'/posts/mk', '/posts/mk', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags/[tag]': RouteRecordInfo<'/tags/[tag]', '/tags/:tag', { tag: ParamValue<true> }, { tag: ParamValue<false> }>,
  }
}
